### ISSUE TITLE
problem link - no data fetch

### ISSUE THREAD

**Issue by jjjeroenski** [Techno11/os-ticket-snipe-it#1]
changed in class.SnipeITIntegrator.php

was:
$snipe_link = $this->getConfig ()->get ( 'url' );  

changed to: (changed twice in same class)
$snipe_link = strip_tags($this->getConfig ()->get ( 'url' ));

even with the "unlink" remark still the <a href= was each time before.

tested with osticket version :  v1.12.2 with skin from : https://osticketawesome.com
snipe-it version: 

v4.7.7 build 4160 (gb8f7cd81e)

**Comment by Techno11** [comment]
Thanks! Fix applied
