### ISSUE TITLE
Link is not created

### ISSUE THREAD

**Issue by geoffken** [Techno11/os-ticket-snipe-it#3]
Using OsTciket v1.14.2, the asset link is not created when creating a ticket or remark. A little bit of research showed me that the API KEY from SnipeIT contained HTML code tags. 

So change at line 204 in "class.SnipeITIntegrator.php" from:
`$api_key = $this->getConfig ()->get ( 'apikey' ) ;`
to this:
`$api_key = strip_tags( $this->getConfig ()->get ( 'apikey' ) );`

After changes it should work fine.

**Comment by Techno11** [comment]
Thanks! Fix was applied
